---
- name: Install monitoring dependencies
  apt:
    name:
      - prometheus-node-exporter
      - collectd
    state: present

- name: Configure node exporter
  systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Create health check script
  template:
    src: health_check.sh.j2
    dest: /usr/local/bin/health_check.sh
    owner: root
    group: root
    mode: '0755'

- name: Create health check cron job
  cron:
    name: "Health check"
    minute: "*/5"
    job: "/usr/local/bin/health_check.sh"
    user: root

- name: Configure collectd
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart collectd

- name: Start and enable collectd
  systemd:
    name: collectd
    state: started
    enabled: yes