version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      rails:
        patterns:
          - "rails*"
          - "actioncable"
          - "actionmailbox"
          - "actionmailer"
          - "actionpack"
          - "actiontext"
          - "actionview"
          - "activejob"
          - "activemodel"
          - "activerecord"
          - "activestorage"
          - "activesupport"
      testing:
        patterns:
          - "rspec*"
          - "factory_bot*"
          - "faker"
          - "shoulda-matchers"
          - "database_cleaner*"
          - "simplecov"
          - "webmock"
          - "vcr"

  # JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    groups:
      hotwire:
        patterns:
          - "@hotwired/*"
          - "turbo*"
          - "stimulus*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"