# StreamSource RuboCop Configuration

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  TargetRailsVersion: 8.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'Gemfile.lock'
    - 'config/boot.rb'
    - 'config/application.rb'
    - 'config/environments/production.rb'

Rails:
  Enabled: true

# Keep Rails conventions; allow slightly more flexibility in specs.
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\\A\\s*#.*\\z'
    - '\\A\\s*it\\s.*\\z'
    - '\\A\\s*describe\\s.*\\z'
    - '\\A\\s*context\\s.*\\z'

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 150
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 25
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'
    - 'Guardfile'
    - 'Rakefile'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 8

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 3

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/NestedGroups:
  Max: 4
