#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - python3-pip
  - python3-setuptools
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release

runcmd:
  # Set up Python for Ansible
  - pip3 install ansible
  
  # Create rails user
  - useradd -m -s /bin/bash rails
  - usermod -aG sudo rails
  
  # Set up firewall
  - ufw --force enable
  - ufw allow ssh
  - ufw allow http
  - ufw allow https
  
  # Install fail2ban
  - apt-get install -y fail2ban
  - systemctl enable fail2ban
  - systemctl start fail2ban

final_message: "StreamSource server initialized after $UPTIME seconds"