name: streamsource
region: nyc
services:
  - build_command: bundle install && yarn install && yarn build && yarn build:css && bundle exec rails assets:precompile
    environment_slug: ruby
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/streamsource
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    name: web
    run_command: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0
    source_dir: /
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: SECRET_KEY_BASE
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET