openapi: 3.0.1
info:
  title: StreamSource API V1
  version: v1
  description: API for managing streaming sources
servers:
- url: http://localhost:3000
paths:
  /api/v1/streams:
    get:
      summary: List streams
      tags:
      - Streams
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: JWT Bearer token
      - name: page
        in: query
        required: false
        schema:
          type: integer
        description: Page number
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
        description: Items per page (max 100)
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                        source_url:
                          type: string
                        is_pinned:
                          type: boolean
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
                      per_page:
                        type: integer
        '401':
          description: unauthorized
    post:
      summary: Create stream
      tags:
      - Streams
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: JWT Bearer token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stream:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    source_url:
                      type: string
                    is_pinned:
                      type: boolean
                  required:
                  - name
                  - source_url
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
  /api/v1/streams/{id}:
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
      description: Stream ID
    get:
      summary: Show stream
      tags:
      - Streams
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: JWT Bearer token
      responses:
        '200':
          description: successful
        '404':
          description: not found
    put:
      summary: Update stream
      tags:
      - Streams
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: JWT Bearer token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                stream:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    source_url:
                      type: string
                    is_pinned:
                      type: boolean
      responses:
        '200':
          description: successful
    delete:
      summary: Delete stream
      tags:
      - Streams
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
        description: JWT Bearer token
      responses:
        '204':
          description: no content
  /api/v1/users/signup:
    post:
      summary: User signup
      tags:
      - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    username:
                      type: string
                  required:
                  - email
                  - password
                  - username
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                          email:
                            type: string
                          username:
                            type: string
                      token:
                        type: string
        '422':
          description: unprocessable entity
  /api/v1/users/login:
    post:
      summary: User login
      tags:
      - Authentication
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                          email:
                            type: string
                          username:
                            type: string
                      token:
                        type: string
        '401':
          description: unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT